ALTER TABLE "Card" DROP CONSTRAINT IF EXISTS "Card_wordId_fkey";
ALTER TABLE "Card" DROP CONSTRAINT IF EXISTS "Card_groupId_fkey";
ALTER TABLE "Group" DROP CONSTRAINT IF EXISTS "Group_userId_fkey";
DROP TABLE IF EXISTS "Card";
DROP TABLE IF EXISTS "Group";
DROP TABLE IF EXISTS "Word";
DROP TABLE IF EXISTS "User";
