DROP INDEX IF EXISTS "Card_due_idx";

ALTER TABLE "Card" ADD COLUMN "step" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "Card" ADD COLUMN "isWinStreak" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Card" ADD COLUMN "streak" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Card" DROP COLUMN "due";
ALTER TABLE "Card" DROP COLUMN "stability";
ALTER TABLE "Card" DROP COLUMN "difficulty";
ALTER TABLE "Card" DROP COLUMN "elapsedDays";
ALTER TABLE "Card" DROP COLUMN "scheduledDays";
ALTER TABLE "Card" DROP COLUMN "reps";
ALTER TABLE "Card" DROP COLUMN "lapses";
ALTER TABLE "Card" DROP COLUMN "state";
ALTER TABLE "Card" DROP COLUMN "lastReview";
