name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - production  # Trigger on pull requests to the production branch
  push:
    branches:
      - production  # Also trigger on direct pushes to production

jobs:
  lint-build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: ./frontend/build

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: lint-build-frontend

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: ./frontend/build
            
      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        with:
          flags: "-avz --delete"  # Rsync flags, adjusts as necessary
          local_path: "./frontend/build/"
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}


  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DB_HOST }}" >> ./backend/.env       

      - name: Build backend
        working-directory: ./backend
        run: npm run build  # If you have a build step, otherwise omit this
        
      - name: Deploy to Remote Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_BACKEND_PATH: ${{ secrets.REMOTE_BACKEND_PATH }}
          ARGS: "-rltgoDzvO --delete"  # Optional: rsync options for more control
          EXCLUDE: "/node_modules/"
        with:
          flags: "-avz --delete"  # Rsync flags for file transfer
          remote_path: ${{ secrets.REMOTE_BACKEND_PATH }}
          local_path: "./backend/"
          remote_host: ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
          ssh_port: 22  # Default is 22, change if using a different port

      - name: Run database migrations
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_BACKEND_PATH: ${{ secrets.REMOTE_BACKEND_PATH }}
        with:
          command: "cd ${{ secrets.REMOTE_BACKEND_PATH }} && npm run migrate"

      - name: Restart backend with Forever
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_BACKEND_PATH: ${{ secrets.REMOTE_BACKEND_PATH }}
          APP_ENTRY: ${{ secrets.APP_ENTRY }}
        with:
          command: |
            cd ${{ secrets.REMOTE_BACKEND_PATH }} && \
            forever stop ${{ secrets.APP_ENTRY }} || true && \
            forever start ${{ secrets.APP_ENTRY }}"
