name: Deploy to server

on:
  push:
    branches:
      - production
      - develop

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete" # Optional: rsync options for more control
          SOURCE: "frontend/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.FRONTEND_PATH }}

  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}" >> .env
          echo "MAILER_HOST=${{ secrets.MAILER_HOST }}" >> .env
          echo "MAILER_USER=${{ secrets.MAILER_USER }}" >> .env
          echo "MAILER_PASSWORD=${{ secrets.MAILER_PASSWORD }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      - name: Deploy to Remote Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete" # Optional: rsync options for more control
          SOURCE: "backend/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.BACKEND_PATH }}
