name: Deploy to server

on:
  push:
    paths:
      - 'backend/**'
      - 'shared/**'
    branches:
      - production

env:
  IMAGE_NAME: chinese-laoshi
  REGISTRY: ghcr.io

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DEFAULT_USER_EMAIL=${{ secrets.DEFAULT_USER_EMAIL }}" >> .env
          echo "PG_DATA_HOST_PATH=/var/lib/chineselaoshi/pg" >> .env
          echo "REGISTRY_IMAGE=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest" >> .env

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.repository_owner }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f backend/Dockerfile -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on server
        run: |
          scp -o StrictHostKeyChecking=no ./.env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{secrets.BACKEND_PATH}}/.env
          scp -o StrictHostKeyChecking=no ./docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{secrets.BACKEND_PATH}}/docker-compose.yml
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            cd ${{secrets.BACKEND_PATH}}
            docker compose down || true
            docker compose --env-file .env up -d
          EOF
